// Increase maxDuration for workflow step functions
// This is inherited by the route.js generated by withWorkflow at build time
// KlingAI video generation can take 5-12 minutes, default 300s is not enough
export const maxDuration = 800

export default function Layout({ children }: { children: React.ReactNode }) {
  return children
}
